version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      actions:
        patterns:
          - '*'
# NOTE: add this when using Rust toolchain in the repo
#    ignore:
#      - dependency-name: 'dtolnay/rust-toolchain'
