use crate::handlers::{
    admin_score_upload, cluster_stats, commissions, config, docs, events, global_unstake_hints,
    glossary, health, jito, jito_mev, list_clients, list_providers, list_validators, readiness,
    reports_commission_changes, reports_scoring, reports_scoring_html, reports_staking, rewards,
    take_rates, unstake_hints, uptimes, validator_score_breakdown, validator_score_breakdowns,
    validator_scores, validators_block_rewards, validators_flat, versions, workflow_metrics_upload,
};
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Marinade's Delegation Strategy API",
        description = "This API serves data about validators and their performance.",
        license(
            name = "Apache License, Version 2.0",
            url = "https://www.apache.org/licenses/LICENSE-2.0"
        )
    ),
    components(
        schemas(admin_score_upload::ResponseAdminScoreUpload),
        schemas(cluster_stats::ResponseClusterStats),
        schemas(commissions::ResponseCommissions),
        schemas(take_rates::ResponseTakeRates),
        schemas(config::ConfigStakes),
        schemas(config::ResponseConfig),
        schemas(config::StakeDelegationAuthorityRecord),
        schemas(global_unstake_hints::ResponseGlobalUnstakeHints),
        schemas(list_clients::ResponseClients),
        schemas(list_providers::ResponseProviders),
        schemas(crate::utils::order::OrderDirection),
        schemas(crate::utils::order::OrderField),
        schemas(list_validators::ResponseValidators),
        schemas(reports_commission_changes::CommissionChange),
        schemas(reports_commission_changes::ResponseCommissionChanges),
        schemas(reports_scoring::ResponseReportScoring),
        schemas(reports_staking::ResponseReportStaking),
        schemas(reports_staking::Stake),
        schemas(rewards::ResponseRewards),
        schemas(store::dto::BlockProductionStats),
        schemas(store::dto::ClientDiversityStats),
        schemas(store::dto::ClientLineageStats),
        schemas(store::dto::ClusterStats),
        schemas(store::dto::CommissionRecord),
        schemas(store::dto::TakeRateRecord),
        schemas(store::dto::DCConcentrationStats),
        schemas(store::dto::FeatureSetStats),
        schemas(store::dto::GlobalUnstakeHintRecord),
        schemas(store::dto::UnstakeHintRecord),
        schemas(store::dto::UnstakeHint),
        schemas(store::dto::UptimeRecord),
        schemas(store::dto::IncidentRecord),
        schemas(store::dto::GroupIncidentRecord),
        schemas(store::dto::GroupIncidents),
        schemas(store::dto::EventEpochRecord),
        schemas(store::dto::SettlementRecord),
        schemas(store::dto::PerformanceRecord),
        schemas(store::dto::ValidatorEpochStats),
        schemas(store::dto::ValidatorGroupNode),
        schemas(store::dto::ValidatorGroupRecord),
        schemas(store::dto::ValidatorRecord),
        schemas(store::dto::ValidatorsAggregated),
        schemas(store::dto::ValidatorScoreRecord),
        schemas(store::dto::ValidatorWarning),
        schemas(store::dto::RuggerRecord),
        schemas(store::dto::RugInfo),
        schemas(store::dto::VersionRecord),
        schemas(store::dto::JitoMevRecord),
        schemas(store::dto::JitoRecord),
        schemas(store::dto::ValidatorBlockRewardsRecord),
        schemas(unstake_hints::ResponseUnstakeHints),
        schemas(uptimes::ResponseUptimes),
        schemas(events::ResponseEvents),
        schemas(validator_score_breakdown::ResponseScoreBreakdown),
        schemas(validator_score_breakdown::ScoreBreakdown),
        schemas(validator_score_breakdowns::ResponseScoreBreakdowns),
        schemas(validator_scores::ResponseScores),
        schemas(versions::ResponseVersions),
        schemas(workflow_metrics_upload::ResponseAdminWorkflowMetrics),
        schemas(jito_mev::ResponseJitoMev),
        schemas(jito::ResponseJito),
        schemas(validators_block_rewards::ResponseValidatorsBlockRewards),
    ),
    paths(
        admin_score_upload::handler,
        cluster_stats::handler,
        list_clients::handler,
        list_providers::handler,
        commissions::handler,
        take_rates::handler,
        config::handler,
        docs::handler,
        glossary::handler,
        health::handler,
        list_validators::handler,
        readiness::handler,
        reports_commission_changes::handler,
        reports_scoring_html::handler,
        reports_scoring::handler,
        reports_staking::handler,
        rewards::handler,
        unstake_hints::handler,
        global_unstake_hints::handler,
        uptimes::handler,
        events::handler,
        validator_score_breakdown::handler,
        validator_score_breakdowns::handler,
        validator_scores::handler,
        validators_flat::handler,
        versions::handler,
        workflow_metrics_upload::handler,
        jito_mev::handler,
        jito::handler,
        validators_block_rewards::handler,
    )
)]
pub struct ApiDoc;
