name: Cargo lint and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Not needed in CI, should make things a bit faster
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  # Remove unnecessary WASM build artifacts
  WASM_BUILD_CLEAN_TARGET: 1
  # Stripping symbols and optimizing for binary size
  RUSTFLAGS: -C strip=symbols -C opt-level=s

jobs:
  lint-and-test:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    services:
      postgres:
        image: postgres:17.4
        env:
          POSTGRES_DB: delegation-strategy
          POSTGRES_USER: delegation-strategy
          POSTGRES_PASSWORD: delegation-strategy
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: 🚧 Checkout project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: ⚙️ Install rust compilation dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libudev-dev pkg-config

      - name: 🦿 Install Rust tookchain
        uses: dtolnay/rust-toolchain@e814c742d4444ce2f3f6abddea7faf00161ed941 # 1.88.0
        with:
          components: rustfmt, clippy

      - name: 🧠 Cache Rust dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: 🧭 Run cargo lint
        run: cargo fmt -- --check && cargo clippy

      - name: 🧨 Run cargo tests
        env:
          DS_TEST_POSTGRES_URL: postgresql://delegation-strategy:delegation-strategy@localhost:5432/delegation-strategy
        run: cargo test --all-features
